### ISSUE TITLE
How to copy file from docker compose container to host?

### ISSUE THREAD

**Issue by akrambek** [palantir/docker-compose-rule#103]
Hi all, I would like to know if it is possible to copy file from docker compose container to host and if yes can you please provide an example. Thanks in advance.

**Comment by joelea** [comment]
Hi @akrambek, my first thought is that the way to do this is via docker volumes, which would be specified in your docker-compose file rather than anything to do with docker-compose-rule.

**Comment by akrambek** [comment]
@joelea Thanks! I am using docker-swarm. Is it possible to achieve docker volumes using docker compose + docker swarm.

**Comment by joelea** [comment]
I'm not sure, it depends on exactly what your set up is. However, this is probably something better asked in docker-swarm support channels. docker-compose-rule purely creates a java wrapper around docker-compose functionality and so we don't add anything beyond what swarm will already provide.

**Comment by iamdanfox** [comment]
Closing this out for now because I don't think there's a bug or feature request for docker-compose-rule here
