### ISSUE TITLE
.addAllClusterWaits overwrites previous waits.

### ISSUE THREAD

**Issue by jamesneale** [palantir/docker-compose-rule#118]
```
ClusterWait a,b,c,d;
DockerComposeRule.builder()
  .addClusterWait(a)
  .addAllClusterWaits(ImmutableList.of(b,c,d)
```

Removes cluster wait 'a' from the list of waits. Things then fail in a very non transparent manner.

**Comment by felixdesouza** [comment]
This should only be the case if you use `clusterWaits` as opposed to `addAllClusterWaits`, the `ImmutableDockerComposeRule.Builder` generates this (at least for DCR 0.17.1):
```java
public final Builder addClusterWait(ClusterWait element) {
    clusterWaitsBuilder.add(element);
    return this;
}

public final Builder addClusterWait(ClusterWait... elements) {
    clusterWaitsBuilder.add(elements);
    return this;
}

public final Builder clusterWaits(Iterable<? extends ClusterWait> elements) {
    clusterWaitsBuilder = ImmutableList.builder();
    return addAllClusterWaits(elements);
}

public final Builder addAllClusterWaits(Iterable<? extends ClusterWait> elements) {
    clusterWaitsBuilder.addAll(elements);
    return this;
}
```

_NB: I just deleted the generated javadoc but this is what gets generated :S_

**Comment by iamdanfox** [comment]
Maybe we should switch to immutables "strict builders" to prevent any
mistakes:

"only additive operations are available on collection attributes, and
regular attributes can be set only once"

**Comment by j-baker** [comment]
Noooo! Don't codify the bad api, make the api better!

Sent from my iPhone

On Oct 15, 2016, at 05:55, iamdanfox <notifications@github.com<mailto:notifications@github.com>> wrote:

Maybe we should switch to immutables "strict builders" to prevent any
mistakes:

"only additive operations are available on collection attributes, and
regular attributes can be set only once"

**Comment by joelea** [comment]
the original bug @jamesneale posted would be really bad. @jamesneale are you able to post/show one of us a small repro of the issue to confirm.

Otherwise the addClusterWaits/clusterWaits distinction seems sane, even if I wish `clusterWaits` was called `setClusterWaits` in this case.

**Comment by jamesneale** [comment]
Only evidence I had is anecdotal - test was failing on circle before reordering and not after. It's possible I had .clusterWaits instead - will investigate.

**Comment by iamdanfox** [comment]
@j-baker can you clarify what you meant by "don't codify the bad api"?  It seems like switching to Immutable's strict builder would be pretty easy and would have prevented James' problem above.

**Comment by j-baker** [comment]
Err, thinking about it some more, I suppose its fine. I was referring to #102 when I said bad API, though.
