### ISSUE TITLE
Aggressive shutdown mode doesn't seem to clean up networks that were created

### ISSUE THREAD

**Issue by j-baker** [palantir/docker-compose-rule#120]
It seems to exhaust available networks really quickly. Probably worth following up slaying all the containers with a call to docker-compose down.

**Comment by Gui13** [comment]
Yes, this is important, right now I have a dozen networks that are not working anymore, and I really don't know how to remove them..

**Comment by iamdanfox** [comment]
Good spot.  Could you submit a PR?

In the meantime @Gui13, you can use `docker network ls` and `docker network rm <some id>` to remove these.  (I personally just nuke them all: `docker network rm $(docker network ls -q)`)
