### ISSUE TITLE
DockerMachine fails if "system" and "additional" environment variables are duplicated.

### ISSUE THREAD

**Issue by gsheasby** [palantir/docker-compose-rule#131]
Relevant [code](https://github.com/palantir/docker-compose-rule/blob/master/src/main/java/com/palantir/docker/compose/connection/DockerMachine.java#L100):
```
            Map<String, String> environment = ImmutableMap.<String, String>builder()
                    .putAll(systemEnvironment)
                    .putAll(additionalEnvironment)
                    .build();
```

If you set FOO=bar in the "additional environment", but FOO=bar happens to also be set on the system, this will fail.

Options:
1 - merge the entries, fail if there's a conflict (e.g. FOO=bar, FOO=baz -> fail)
2 - merge the entries, choose additional if there's a conflict (e.g. system FOO=bar, add. FOO=baz -> FOO=baz).

**Comment by SerialVelocity** [comment]
Please option 2 otherwise if people want to override system properties they need to change the system environment.
