### ISSUE TITLE
Publish to maven central?

### ISSUE THREAD

**Issue by davidkarlsen** [palantir/docker-compose-rule#136]
Would you consider pushing the releases to maven central and/or jcenter?
The library seems very useful, and it would be handy to access releases through our maven proxy.

**Comment by joelea** [comment]
Unfortunately, I think this is unlikely to happen. Currently all of our open source java libraries are hosted in the same way and there is a time and complexity cost to setting up and managing separate locations for the jars. Adding an extra maven repository (at the project or proxy level) is normally straightforward, so it's not something that seems worth that cost right now.

Is there a particular reason why you can't use the current location? As I said above, solving this is *normally* relatively straightforward, but I know there's always the possibility of unique issues.

**Comment by joelea** [comment]
Closing this due to lack of response, but happy to carry on the conversation if there's some extra context which makes this make more sense.

**Comment by mfriedenhagen** [comment]
Hello @joelea, while I understand that switching from bintray to maven-central is a big step, adding your palantir repository to jcenter seems to be easy: https://bintray.com/docs/usermanual/formats/formats_mavenrepositories.html#_jcenter

**Comment by bduisenov** [comment]
Hi @iamdanfox @joelea @hpryce!
Could you consider linking docker-compose-rule-junit4 to jcenter as @mfriedenhagen suggested?

Cheers,
Babur

**Comment by davidkarlsen** [comment]
@joelea Any comment on this?
