### ISSUE TITLE
Junit 5 extension

### ISSUE THREAD

**Issue by jcustenborder** [palantir/docker-compose-rule#138]
What are the thoughts about a junit 5 extension? I've done some work in a private repo that I could contribute.

**Comment by hpryce** [comment]
One of the things we've been thinking of is splitting the core of the library and the junit part into two separate projects. That way consumers can decide whether or not they want the junit (4) bindings or just want to get the raw classes for managing the lifecycle of a docker-compose cluster. If that happened we could really easily have a junit 5 project that independently added support. How does this sound? The project split should be relatively straightforward but I think needs changes to the bintray publishing so it would probably need to be done by me or @joelea.

**Comment by joelea** [comment]
@hpryce sounds like we should actually get round to it now. 

@jcustenborder would you be happy maintaining the junit 5 bindings independently or would you want us to bring it under the umbrella of core + junit 5?

**Comment by jcustenborder** [comment]
@hpryce That is what I was thinking. It would be great if the core docker-compose library was in another project. It's useful enough that it could easily be it's own project. Then I could pull it in for the JUnit 5 extension.

@joelea I'm open to hosting it under jcustenborder. The only weirdness is that I don't have any experience with bintray. I deploy to central.

**Comment by joelea** [comment]
@hpryce merged #140 which splits out the projects, but our publishing was slightly wrong. We'll fix that soon and then you should be able to do what you want with the "core" section.

**Comment by jcustenborder** [comment]
Thanks @joelea and @hpryce! Much appreciated!

**Comment by joelea** [comment]
@jcustenborder this split has now happened. It is very unlikely to have been split up perfectly to make this trivial. My thinking is that it would be best to implement a JUnit 5 version by copy pasting code from the JUnit 4 version when necessary, and then we can go through a process of deduplication once we figure out what the solution looks like.

**Comment by tobad357** [comment]
@jcustenborder did you progress with the junit5 work
I'm interested in it as we need BeforeAll and AfterAll in junit5 

I would be happy to help out if needed

@joelea has any work progressed anywhere else?

**Comment by c100k** [comment]
@tobad357 if you want to use it from now in one of your project, here is a small workaround to make it work waiting for a new release with Junit5 support : https://github.com/c100k/docker-compose-rule-with-junit5.

Not sure if it works at 100% in all cases but in mine it does the job.

**Comment by fryz** [comment]
This looks like it was refiled at https://github.com/palantir/docker-compose-rule/issues/224 and is being worked on in https://github.com/palantir/docker-compose-rule/pull/223
