### ISSUE TITLE
Large image pulls - any logging?

### ISSUE THREAD

**Issue by fzakaria** [palantir/docker-compose-rule#142]
It would be great to have an ongoing log collector for the image pulls.
Perhaps if the images were fetched before compose using a docker java client (https://github.com/docker-java/docker-java) they can be prefetched and it includes logging of the progress.

**Comment by joelea** [comment]
Hey @fzakaria - what would this help with? It's not something I've come across wanting before so just want to understand what this would need to provide to be useful.

**Comment by fzakaria** [comment]
Right now, you just sit idly by as images are pulled.
If you have a case where network is slow and image is large (multiple GB) there is little feedback.

It would be great to just capture the image pulling output when `docker-compose up` is executed.
So you can see the image layers being updated.

**Comment by joelea** [comment]
Hey @fzakaria,

Turns out we have something that does this already, it's just not documented (apologies for that). The output of each docker-compose command is logged at the TRACE level. Could you see if this is sufficient for what you need?

**Comment by fzakaria** [comment]
thanks ill close
