### ISSUE TITLE
Unable to connect to a remote machine

### ISSUE THREAD

**Issue by cbevin** [palantir/docker-compose-rule#145]
I'm unable to get docker-compose-rule to connect to my remote docker daemon running as a swarm manager on Ubuntu. I've created several docker machines in a swarm cluster, and when running "docker-machine ls" on my server I can see that my manager is running and accessible at tcp://192.168.99.101:2376. 

Using nmap I can see that this port is open and the IP address is accessible. 

However when creating a DockerMachine using the remote api as in your example, and passing it to the builder for DockerComposeRule, I get the error:

"Couldn't connect to Docker daemon - you might need to run `docker-machine start default`"

Any help to get this working would be appreciated.

**Comment by joelea** [comment]
Hey @cbevin,

Would you be able to post a snippet of the code that doesn't work?

**Comment by cbevin** [comment]
Sure, following your example I create a docker machine:

`private final DockerMachine dockerMachine = DockerMachine.remoteMachine().host("tcp://192.168.99.101:2376").build();`

And then simply attempt to use this within the DockerComposeRule:

final String pName = this.getProjectName();
DockerComposeRule.builder().files(files).projectName(new ProjectName() {
				@Override
				protected String projectName() {
					return pName;
				}
}).machine(dockerMachine);

BTW, if I setup my terminal with the appropriate eval() statement for my swarm master, I can use docker-compose on the command line to deploy the services.

**Comment by CRogers** [comment]
Hi @cbevin,

To help us diagnose what's going on can you please run `docker -H tcp://tcp://192.168.99.101:2376 info` and paste what it returns? I've used DCR to hit a Swarm on a former project, I'm going to check how we did it there.

**Comment by CRogers** [comment]
@cbevin Is your swarm manager using TLS? If so, you may need to use the `withTLS(String certificatePath)` method on the builder you get from `DockerMachine.remoteMachine()` which will set the correct environment variables (if running from the command line then these environment vars will be correct, however when running from IDEA these are unlikely to get propagated unless you change the run configuration). The correct value of `certificatePath` is likely to be whatever the `DOCKER_CERT_PATH` env var is in your terminal.

If you are running without TLS, you may need to call the `withoutTLS(...)` method to ensure that the `DOCKER_TLS_VERIFY` env var is not being propagated when we call through to docker.

**Comment by CRogers** [comment]
(btw, you can use `ProjectName.fromString(...)` rather than making a new anonymous inner class.

**Comment by cbevin** [comment]
Looks like that was all it was! Thanks for your help!
