### ISSUE TITLE
ConflictingContainerRemovingDockerCompose fails to detect conflicting container names

### ISSUE THREAD

**Issue by zeroorone13** [palantir/docker-compose-rule#189]
As of https://github.com/docker/docker/commit/c9d0a77657ccc3be144ed4de12d43c8cfcca8590 the conflicting container name message coming from Docker uses the format "The container name" rather than the previous format "The name" which `ConflictingContainerRemovingDockerCompose` expects. This causes `getConflictingContainerNames` to fail to detect the conflicting names. Relaxing the regular expression to handle both would easily solve this issue.

Tested with:
* Docker version 17.03.0-ce, build 60ccb22
* docker-compose-rule version 0.31.1

**Comment by iamdanfox** [comment]
Merged #194 containing a fix!
