### ISSUE TITLE
Pull images on startup

### ISSUE THREAD

**Issue by jonesr91** [palantir/docker-compose-rule#204]
I can see from the documentation that I am able to do something like the following:

    public class DockerCompositionTest {
        @ClassRule
        public static DockerComposition composition = DockerComposition.of("src/test/resources/docker-compose.yml")
            .pullOnStartup(true)
            .build();
    }

But I can also see that DockerComposition is deprecated.

Is this available (or any plans for this to become available) via the DockerComposeRule object?

Thanks,
Ryan

**Comment by mdotson** [comment]
This already exists on the `DockerComposeRule` object: https://github.com/palantir/docker-compose-rule/blob/master/docker-compose-rule-junit4/src/main/java/com/palantir/docker/compose/DockerComposeRule.java#L122

**Comment by sebastientromp** [comment]
It looks like the Builder doesn't expose the `pullOnStartup` property though. Am I missing something?
