### ISSUE TITLE
Bintray latest maven dependency doesn't have latest code

### ISSUE THREAD

**Issue by adamboesch** [palantir/docker-compose-rule#207]
The latest 0.32 dependency doesn't seem to have #193 in it. My pom contains the following:

```
<dependency>
    <groupId>com.palantir.docker.compose</groupId>
    <artifactId>docker-compose-rule-junit4</artifactId>
    <version>0.32.0</version>
</dependency>
```

**Comment by uschi2000** [comment]
Looks like the jcenter synchronization is broken, the artifacts do appear on Bintray, but not on JCenter: https://palantir.bintray.com/releases/com/palantir/docker/compose/docker-compose-rule-core/

**Comment by uschi2000** [comment]
@iamdanfox can you take a look?

**Comment by shiyardavid** [comment]
Hello,
I have the same issue:
Missing artifact com.palantir.docker.compose:docker-compose-rule-junit4:jar:0.32.0

**Comment by dotCipher** [comment]
@uschi2000 / @iamdanfox what action is needed here?
