### ISSUE TITLE
Wrong Maven coordinates?

### ISSUE THREAD

**Issue by thokari** [palantir/docker-compose-rule#214]
I get this error:

`Could not resolve: com.palantir.docker.compose:docker-compose-rule:0.32.1`
`Could not resolve: com.palantir.docker.compose:docker-compose-rule-core:0.32.1`
`Could not resolve: com.palantir.docker.compose:docker-compose-rule-junit4:0.32.1`

Is maybe the file / folder structure on Bintray not correct?

**Comment by rion18** [comment]
Have you added the correct repository?

IE on Maven,

```
  <repositories>
    <repository>
      <id>palantir</id>
      <url>https://dl.bintray.com/palantir/releases</url>
    </repository>
  </repositories>
```

**Comment by thokari** [comment]
Probably...
