### ISSUE TITLE
JUnit5

### ISSUE THREAD

**Issue by dotCipher** [palantir/docker-compose-rule#224]
[Junit 5](http://junit.org/junit5/docs/current/user-guide/#overview) has recently released it's stable platform versions and I have been using it in multiple projects without any problems.  I would love to use DCR for these projects instead of having to use [`junit-jupiter-migrationsupport`](http://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4-rule-support) since `@Rule` and `@ClassRule` went away.

See [Junit4 -> 5 Migration Tips](http://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4-tips) for other notes.

**Comment by dotCipher** [comment]
Tracking completion of this on #223

**Comment by naxhh** [comment]
What is the status of this? I see #223 has been closed

**Comment by CRogers** [comment]
@naxhh JUnit 5 is fully supported, see https://github.com/palantir/docker-compose-rule#junit-5
