### ISSUE TITLE
Wait for service by expecting a certain log

### ISSUE THREAD

**Issue by iikirilov** [palantir/docker-compose-rule#238]
I have two compose files that I need to run. The first one needs to run and I need to wait until one of the containers drops the log message "BOOTED" before I spin up the second set of containers. Is there a way to accomplish this using this library?

**Comment by robd** [comment]
@iikirilov I wasn't able to work out how to do this, so I ended up using https://www.testcontainers.org/usage/docker_compose.html which supports that feature.
