### ISSUE TITLE
Generate a unique cluster name for each run

### ISSUE THREAD

**Issue by joelea** [palantir/docker-compose-rule#29]
docker-compose by default gives each cluster the name of the directory it's in. This is going to cause issues when running tests in parallel etc.

We can fix this by using `--project-name` flag when using docker compose combined with a random name/id for each cluster.

**Comment by gbrova** [comment]
+1!  We're coming across the parallel run issue on Pict now.

**Comment by CRogers** [comment]
@joelea Have you started working on this feature? Otherwise we're going to do it now.

**Comment by joelea** [comment]
Looks like this is fixed?
