### ISSUE TITLE
Output logging errors

### ISSUE THREAD

**Issue by nemines** [palantir/docker-compose-rule#39]
I've been running tests with the docker-compose-rule from IntelliJ Idea.
The errors are correctly caught but are not outputted anywhere.

Due to misconfigurations, Intellij fails with only a stacktrace and no significant error message.

**Comment by joelea** [comment]
SL4J logging is just not appearing, probably a docs issue, or we need to log differently.

**Comment by CRogers** [comment]
We also have problems with SLF4J and get no errors messages or any logging. I would consider injecting loggers so we can choose how we output logs.

**Comment by CRogers** [comment]
More problems with static logging: I've now managed to force gradle to change it's SLF4J log level in all the requisite places, but since DCR uses debug for basically everything I then get a whole load of noise from the other libraries I use and I don't care about. Really I want all the logs from just DCR, but no logs from the other libraries.

**Comment by joelea** [comment]
Yeah, I want to play with a better pattern to fix this, but I'm not going to have time in the near future.

Can you not configure an actual logging file with gradle to do this? This is exactly the kind of feature things like logback and log4j support - "Please give me DEBUG on this package but WARN on everything else".

**Comment by joelea** [comment]
Next time I take part in writing a library, I'll insist we have more flexible logging.

**Comment by CRogers** [comment]
Gradle forces use to use it's own SLF4J logger, which does not have those features. If you try to add log4j you get the multiple static binders error and gradle wins :(

**Comment by joelea** [comment]
Well that sucks :(

Guess we'll have to do something about this then.

**Comment by joelea** [comment]
Release 0.6.0 fixes some of this pain, but we still need something better.

**Comment by fryz** [comment]
@nemines / @CRogers - is this still an issue / relevant?

**Comment by fryz** [comment]
Closing out as inactive - let us know if this is still an issue
