### ISSUE TITLE
Docker-compose --project is randomly chosen

### ISSUE THREAD

**Issue by j-baker** [palantir/docker-compose-rule#40]
DCR 0.5.3 randomly chooses the project name every single test run.

This seems like an unsafe default:

- if the JVM exits during startup (I cancelled a build), the next run won't shut down or delete the containers that were created in the last run
- if you use named containers and this happens, you won't be able to run the tests again, until you have manually deleted all the containers used in the last run
- you can't easily use docker-compose logs to view the logfiles being created

I reverted to 0.5.2 :+1:

**Comment by CRogers** [comment]
I think the real solution here is to allow you to choose your own project name. Randomly generated project names are the safe default if you `up` the same docker-compose file in parallel.

Also, stop using `ExternalRule` as it doesn't have the behaviour you expect - you want to always run `after()`, even if there is was an exception.

**Comment by iamdanfox** [comment]
PR#53 allows you to specify a project name instead of a randomly chosen one. This should be good to close when the next release comes out.

**Comment by iamdanfox** [comment]
0.9.0 lets you specify a `ProjectName`. @CRogers OK to close?

**Comment by CRogers** [comment]
Go for it

**Comment by iamdanfox** [comment]
I don't have admin rights, sorry.

**Comment by CRogers** [comment]
You do now!
