### ISSUE TITLE
Sync jars with Maven Central

### ISSUE THREAD

**Issue by tzolov** [palantir/docker-compose-rule#433]
Currently the jar artifacts are accessible only via the Bintray maven repository. Later is fine for testing/experimenting but useful for production environments where the Maven Central is the standard. 
Demanding an additional (custom) Bintray repository imposes unnecessary configuration changes, opens additional security risks and often impacts the overall performance in resolving  artifacts. 

Without changing the current palantir build/release pipeline, it should be trivial to sync the existing released artifacts form Bintray to Maven Central. Here are some references: 
* https://www.jfrog.com/confluence/display/BT/Syncing+with+Third-Party+Platforms
* https://central.sonatype.org/pages/requirements.html
* https://stackoverflow.com/questions/54636347/how-to-sync-maven-artifact-from-jcenter-to-maven-central

Unlike #136 and #205 i'm **not** looking into replacing Bintray as being the primary repository but just to sync the already released artifacts to Maven Central.

Please let me know if i can help with the initial configuration?

The ability to access the artifacts from Maven Central is a decisive for my organization. It will determine whether to use (and contribute to) the palantir:docker-compose-rule project or to fork and maintain it by ourself.

**Comment by iamdanfox** [comment]
I've kicked off a ticket internally to get the syncing set up. I don't have access to the Palantir credentials to be able to do this myself I'm afraid, but I know other Palantir open source projects have been synced successfully (e.g. [tracing](https://mvnrepository.com/artifact/com.palantir.tracing/tracing)), so I think this should be doable!

**Comment by peterwvj** [comment]
Any progress on this? @iamdanfox @palantirtech

**Comment by tzolov** [comment]
Guys, i hope that you are aware Bintray and JCenter are gone and the clock is ticking: https://bit.ly/30vhVEB

> What happens after the sunset of Bintray and JCenter?
> On May 1, 2021, the sunset will impact all existing Bintray users. Bintray users will be blocked and will no longer be able to use the Bintray service. This includes existing software distribution, account administrative access, UI access, and the REST API.
> After this date JCenter repository will still resolve artifacts, but end users should migrate to the canonical repo (e.g. Java packages should be retrieved from Maven Central). On Feb 1st, 2022 JCenter will only resolve artifacts for Artifactory clients.

**Comment by mikeholler** [comment]
I see that this bintray repository is proxied through maven central, but clicking on this link, which leads to the repository, results in a "Forbidden!" message now when last week it did not.

Artifact page:

https://mvnrepository.com/artifact/com.palantir.docker.compose/docker-compose-junit-jupiter/1.5.0

![Screenshot from 2021-04-12 12-58-04](https://user-images.githubusercontent.com/1164112/114439754-f56aa380-9b8e-11eb-9007-bceb0606fee1.png)

Direct download link (from the "files" link in the page above)

https://dl.bintray.com/palantir/releases/com/palantir/docker/compose/docker-compose-junit-jupiter/1.5.0/docker-compose-junit-jupiter-1.5.0.jar

**Comment by mikeholler** [comment]
The problem I posted, just above, appears to be resolved... :thinking:

**Comment by pgribnau** [comment]
> The problem I posted, just above, appears to be resolved... 🤔

Probably from the scheduled brown-out: https://status.bintray.com/incidents/4mzph0y8l6hk

This will be a problem once Bintray is sunset May 1st.

**Comment by uschi2000** [comment]
Acknowledged, we're working on it. (I think this is one of the last few repos that haven't migrated yet.)

**Comment by jvalkeal** [comment]
There's still some bits missing like:
```
Failed to collect dependencies at com.palantir.docker.compose:docker-compose-junit-jupiter:jar:1.4.2
  -> com.palantir.docker.compose:docker-compose-rule-core:jar:1.4.2
  -> com.palantir.conjure.java.runtime:conjure-java-jackson-serialization:jar:4.18.1
```

**Comment by gelin** [comment]
Are there any news?

`com.palantir.conjure.java.runtime:conjure-java-jackson-serialization:jar:4.18.1` is not available in Maven Central.
There are newer versions of `conjure-java-jackson-serialization`, however, `docker-compose-rule-core:1.5.0` (the latest release) depends on `4.18.1`.

Could you update the `docker-compose-rule-core` at least?

**Comment by gelin** [comment]
Or just upload `com.palantir.conjure.java.runtime:conjure-java-jackson-serialization:jar:4.18.1` to Maven Central. Please :pray:
