### ISSUE TITLE
saveToLogs does not save logs

### ISSUE THREAD

**Issue by verity** [palantir/docker-compose-rule#44]
V0.5.3

When using the following class rule, it creates the log directory, but never writes any container log files.

`@ClassRule
    public static final DockerComposition composition = DockerComposition.of("src/test/resources/full-stack/docker-compose.yml").saveLogsTo("build/docker-logs/dockerSuite").build()`

Debugging the code, I can see that in FileLogCollector.java > startCollecting
 `ContainerNames containerNames = dockerCompose.ps();` always returns empty.

The docker ps output contains a result, however `ContainerNames.parseFromDockerComposePs(psOutput)` is empty.

ContainerNames.java -> getContainerNamesAtStartOfLines seems to be the cause.

The psContainerOutput value it is trying to parse is:

> gaia       service/bin/gaia server va ...   Up      0.0.0.0:17000->17000/tcp, 0.0.0.0:17001->17001/tcp, 8000/tcp, 8001/tcp, 8443/tcp 
> selenium   /opt/bin/entry_point.sh          Up      0.0.0.0:4444->4444/tcp, 0.0.0.0:5900->5900/tcp

**Comment by verity** [comment]
Upgrading the docker-compose file to V2 fixed this issue for me.

**Comment by joelea** [comment]
Is this linked to #38 ?

**Comment by CRogers** [comment]
@verity did originally use `container_name`s in her docker-compose file - just single words with no underscores iirc. This probably also triggered the bug, as there where no underscores for DCR to look for.

**Comment by joelea** [comment]
yeah, this would've triggered it. The underscore bug was separate from this whole concept. I like that people tend to hit bugs in big clumps.

**Comment by CRogers** [comment]
Basically, the container name in `docker-compose ps` can be anything.

**Comment by joelea** [comment]
Yep, it's the same as #38, we'll need to pretty aggressively change how we grab container names.

**Comment by joelea** [comment]
Fixed!
