### ISSUE TITLE
Force purge of existing containers with conflicting name. 

### ISSUE THREAD

**Issue by rsltrifork** [palantir/docker-compose-rule#64]
After an unclean shutdown, running containers will remain, and hinder a repeated test with the error:
``` "Conflict. The name "/docker-contianer-name" is already in use by container 04a0cb1433e1c325ac43a52d0bfa6b0b2ae6ba6665753d50dab7f235a6768645. You have to remove (or rename) that container to be able to reuse that name.```

Please add an option to the builder interface to catch that, and automatically delete the existing container and retry starting it. I can do a PR if you want.

**Comment by joelea** [comment]
This sounds entirely sensible - a PR would be great. Thanks!

**Comment by nmiyake** [comment]
Have a PR that mostly does this, but have been fighting with CircleCI on unit tests -- CircleCI doesn't support the "remove" operation and the "rename" behavior seems funky as well. Also have 2 different flavors of the PR -- one that refactors quite a bit (but thus causes API breaks) and another that is purely additive, but has code duplication. Any preference between the two from the project perspective?

Heading out now, but will clean this up and re-submit tomorrow morning (Pacific time).

**Comment by nmiyake** [comment]
PR in progress at #73 to address this issue
