### ISSUE TITLE
Add option to remove volumes on shutdown

### ISSUE THREAD

**Issue by tonio-ramirez** [palantir/docker-compose-rule#70]
I just noticed my disk had been gobbled up by multiple dangling volumes, from running tests using this rule.  An option (maybe even defaulting to `true`) to remove volumes on shutdown would be great.

**Comment by joelea** [comment]
I think it's probably fine to always clean up the volumes given that's what most usages probably expect. If people want to use them for debugging then `skipShutdown` is available. I'm also happy to add an option to not remove volumes if a case appears I'm not thinking of right now.

WIll be fixed by #71

**Comment by tonio-ramirez** [comment]
Oh great!  I had actually just forked the repo to work on a PR... happy to learn I don't even have to do that!

**Comment by joelea** [comment]
This should become available as part of 0.13.0 which is publishing now (you can check the download badge in the README to see when it's published).

**Comment by tonio-ramirez** [comment]
Just tried out the new version, still seeing dangling containers after shutdown.  After investigating, I noticed that `docker-compose rm -v` was returning "No stopped containers", and hence was doing nothing.  Turns out that `down` not only stops, but also removes, the containers.  There is a `-v` option on `down`, which also removes volumes.

**Comment by joelea** [comment]
Whoops. Looks like I fixed it for < 1.6 only :( Sorry about that.

There's been some debate about how to best handle a variety of versions of docker-compose that are in use - the eventual conclusion was lets keep it simple till it bites us. Looks like this is the time to come up with a more sensible plan. It's not at all obvious what's getting run anymore.

**Comment by tonio-ramirez** [comment]
Is this being published?

**Comment by joelea** [comment]
Publishing now.
