### ISSUE TITLE
Should support Docker for Mac

### ISSUE THREAD

**Issue by jchomicki** [palantir/docker-compose-rule#83]
Now that the Docker for Mac Beta is open to the public, docker-compose-rule should not default to 'remote' if the OS is Mac. This causes docker-compose-rule to fail on Mac's that are running Docker for Mac since the expected environment variables do not exist.

**Comment by felixdesouza** [comment]
This has been fixed in the latest version of docker compose rule.

**Comment by jchomicki** [comment]
@felixdesouza I see that now, hit some gradle caching issues locally. I'll close this out!
